### ISSUE TITLE
hpp apparently doesn't build under 7.8

### ISSUE THREAD

**Issue by bananu7** [acowley/hpp#1]
I've a library utilizing `GLUtil` (thanks, by the way :)), which after your recent swap to `hpp` broke [my CI build](https://circleci.com/gh/bananu7/Hate/14).

I've 7.10 on my local machine and here everything is fine. It seems like a problem with expecting `pure` to be implicitly imported (refer to the build log for details).

**Comment by acowley** [comment]
Ack, sorry, that's no good. I'll fix it asap.

**Comment by acowley** [comment]
This *should* be fixed in master, but my Travis builds blew up for not-my-fault reasons, iiuc. Can you give it a shot from git, or do you need it on hackage first?

**Comment by bananu7** [comment]
Sorry for the łatę reply; I can certainly get the git version on my other machine (7.8) if I can reproduce the behaviour. Hopefully I'll have some info tomorrow.

**Comment by bananu7** [comment]
It still seems to have problems under 7.8. I've switched to 7.10 on CI for now, so that's less important for me, but you might still wanna investigate.

**Comment by acowley** [comment]
Thanks, I'll have another go at getting the Travis configuration sorted out.

**Comment by acowley** [comment]
After all this time, I'm going to say that 7.8 isn't supported unless someone specifically requests it.
