### ISSUE TITLE
Add dependency logging

### ISSUE THREAD

**Issue by treeowl** [acowley/hpp#5]
When preprocessing a file, the caller may be very interested in which files are read in order to track dependencies. This may well be possible already, but not in a particularly obvious way.

**Comment by acowley** [comment]
That is a great idea! It could fit into the interpreter that handles file IO. I will try to take a look at exposing this soon.

**Comment by acowley** [comment]
I added the feature on the [`files-read`](https://github.com/acowley/hpp/commits/files-read) branch in this [commit](https://github.com/acowley/hpp/commit/13f9951e3db0f222c3cd2ff10ac90fc320c811ba). Figuring out the most convenient way of exposing this data to library users should be all that is left.

**Comment by treeowl** [comment]
Thanks! I should let you know this ticket was directly inspired by [GHC Trac #1290](https://ghc.haskell.org/trac/ghc/ticket/1290). There's no guarantee that GHC will even actually try to do that, but if it does, having support for it in `hpp` would be helpful.

**Comment by acowley** [comment]
Added in 13f9951e3db0f222c3cd2ff10ac90fc320c811ba
